name: Test architecture matrix
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [armv6l] #, armv7l, aarch64]
        include:
        - arch: armv6l
          cpu: arm1176
          base_image: raspios_lite:latest
          cpu_info: raspberrypi_zero_w

    steps:
    - uses: pguyot/arm-runner-action@v2
      with:
        base_image: ${{ matrix.base_image }}
        cpu: ${{ matrix.cpu }}
        cpu_info: ${{ matrix.cpu_info }}
        commands: |
            bash -c "
            set -ex &&
            apt-get update && 
            apt-get install -y build-essential git &&
            git pull povlhp/zeroW-crosscompile &&
            cd zeroW-crosscompile &&
            gcc test.c -o /tmp/test &&
            pwd >/tmp/pwd
            "
        copy_artifact_path: /tmp/
        copy_artifact_dest: artifacts        # on the runner

      - name: Upload binary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: artifacts/	
          
